<?php echo $this->doctype(); ?>

<html lang="pt-br">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        <?php
        
echo $this->headLink(
                array(
                        'rel' => 'shortcut icon',
                        'type' => 'image/vnd.microsoft.icon',
                        'href' => $this->basePath() . '/img/favicon.ico'
                ))
            ->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-social.css')
            ->prependStylesheet( $this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>

        <!-- Scripts -->
        <?php
        
echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        // ->prependFile($this->basePath() . '/js/respond.min.js',
        // 'text/javascript', array('conditional' => 'lt IE 9',))
        // ->prependFile($this->basePath() . '/js/html5shiv.js',
        // 'text/javascript', array('conditional' => 'lt IE 9',))
        	?>	
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>"> <img
					src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
					alt="Zend Framework 2" />&nbsp;<?php echo $this->translate('ClickMark Digital')?>
				</a>
			</div>
			<?php echo $this->render('layout/menu/navMenu.phtml')?>
			
			<!--/.navbar-collapse -->
		</div>
	</nav>

	<div class="content">
		<div class="container">
		
		<?php $flashMessenger = $this->flashMessenger();
    
    if ($flashMessenger->hasCurrentWarningMessages()) :
        ?>
			     <?php $flashMessenger->setNamespace("warning"); ?>
			     <?php foreach ( $flashMessenger->getMessages () as $msg ) : ?>
			     <div class="alert alert-warning alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<strong>Aviso!</strong> <?php echo $msg; ?>
				</div>
				<?php endforeach; ?>
				<?php endif; ?>
								
				<?php if( $flashMessenger->hasCurrentErrorMessages () ) : ?>
			     <?php $flashMessenger->setNamespace("error"); ?>
			     <?php foreach ( $flashMessenger->getMessages () as $msg ) : ?>
			     <div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<strong>Erro!</strong> <?php echo $msg; ?>
				</div>
				<?php endforeach; ?>
				<?php endif; ?>
				
				<?php if( $flashMessenger->hasCurrentSuccessMessages () ) : ?>
			     <?php $flashMessenger->setNamespace("success"); ?>
			     <?php foreach ( $flashMessenger->getMessages () as $msg ) : ?>
			     <div class="alert alert-success alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<strong>Sucesso!</strong> <?php echo $msg; ?>
				</div>
				<?php endforeach; ?>
				<?php endif; ?>
				
				<?php if( $flashMessenger->hasCurrentInfoMessages () ) : ?>
			     <?php $flashMessenger->setNamespace("info"); ?>
			     <?php foreach ( $flashMessenger->getMessages () as $msg ) : ?>
			     <div class="alert alert-info alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<strong>Informação!</strong> <?php echo $msg; ?>
				</div>
				<?php endforeach; ?>
				<?php endif; ?>
		
				<?php echo $this->content?>
                <hr>
		</div>
		<!-- /container -->
	</div>
	<div class="footer">
		<div class="container">
			<footer>
				<p>&copy; ClickMark Digital <?php echo date('Y') ?></p>
			</footer>
		</div>
	</div>


	<!-- Bootstrap core JavaScript
        ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="/js/bootstrap.min.js"></script>
        <?php echo $this->inlineScript()?>
    </body>
</html>
