<?php
use Zend\Session\Container;
$session = new Container('user');
?>
<div class="collapse navbar-collapse navbar-left">
	<ul class="nav navbar-nav">
		<li class="active"><a href="#">Home</a></li>
<?php if ( $session->login ) { ?>

<!-- Collect the nav links, forms, and other content for toggling -->
		<li class="dropdown"><a href="#" class="dropdown-toggle"
			data-toggle="dropdown">User Options <span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<li><a href="#">Action</a></li>
				<li><a href="#">Another action</a></li>
				<li><a href="#">Something else here</a></li>
				<li class="divider"></li>
				<li><a href="#">Separated link</a></li>
				<li class="divider"></li>
				<li><a href="#">One more separated link</a></li>
			</ul></li>
    <?php } ?>
    	<li><a href="/about">Sobre</a></li>
    <?php if ( $session->login ) { ?>
        <li><a href="/prov">Sistema Provisório</a></li>
    <?php } ?>
	</ul>
</div>
<!-- /.navbar-collapse -->