<?php
if (is_object($form)) {
    // within a view script
    $form = $this->form;
    
    // $form->setAttribute('action', $this->url('cadastro', array('action' =>
    // 'index')));
    $form->setAttributes(
            array(
                    'action' => '/auth',
                    'method' => 'POST',
                    'role' => 'form'
            ));
    
    $form->prepare();
    ?>

    <div class="row" style="margin-top:20px">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<?php echo $this->form()->openTag($form)?>
			<fieldset>
				<h2><?php echo $this->translate('Please Sign In'); ?></h2>
				<hr class="colorgraph">
				<div class="form-group">
					<?php echo $this->formElement($form->get('authEmail')->setAttribute('class','form-control input-lg')->setAttribute('placeholder',$this->translate('Email Address')))?>
					<small><span class="text-danger"><?php echo $this->formElementErrors($form->get('authEmail')) ?></span></small>
				</div>
				<div class="form-group">
                    <?php echo $this->formElement($form->get('authPassword')->setAttribute('class','form-control input-lg')->setAttribute('placeholder',$this->translate('Password')))?>
					<small><span class="text-danger"><?php echo $this->formElementErrors($form->get('authPassword')) ?></span></small>
				</div>
				<span class="button-checkbox">
					<button type="button" class="btn" data-color="info"><?php echo $this->translate('Remember Me'); ?></button>
                    <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">
					<a href="" class="btn btn-link pull-right"><?php echo $this->translate('Forgot Password?'); ?></a>
				</span>
				<hr class="colorgraph">
				<div class="row">
					<div class="col-xs-6 col-sm-6 col-md-6">
                        <input type="submit" class="btn btn-lg btn-success btn-block" value="<?php echo $this->translate('Log In'); ?>">
					</div>
					<div class="col-xs-6 col-sm-6 col-md-6">
						<a href="/register" class="btn btn-lg btn-primary btn-block"><?php echo $this->translate('Register'); ?></a>
					</div>
				</div>
			</fieldset>
		<?php echo $this->form()->closeTag($form)?>
	</div>
</div>

<style>
<!--
/* Credit to bootsnipp.com for the css for the color graph */
.colorgraph {
  height: 5px;
  border-top: 0;
  background: #c4e17f;
  border-radius: 5px;
  background-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
  background-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1 87.5%, #62c2e4 87.5%, #62c2e4);
}
-->
</style>
<script type="text/javascript">
<!--
$(function(){
    $('.button-checkbox').each(function(){
		var $widget = $(this),
			$button = $widget.find('button'),
			$checkbox = $widget.find('input:checkbox'),
			color = $button.data('color'),
			settings = {
					on: {
						icon: 'glyphicon glyphicon-check'
					},
					off: {
						icon: 'glyphicon glyphicon-unchecked'
					}
			};

		$button.on('click', function () {
			$checkbox.prop('checked', !$checkbox.is(':checked'));
			$checkbox.triggerHandler('change');
			updateDisplay();
		});

		$checkbox.on('change', function () {
			updateDisplay();
		});

		function updateDisplay() {
			var isChecked = $checkbox.is(':checked');
			// Set the button's state
			$button.data('state', (isChecked) ? "on" : "off");

			// Set the button's icon
			$button.find('.state-icon')
				.removeClass()
				.addClass('state-icon ' + settings[$button.data('state')].icon);

			// Update the button's color
			if (isChecked) {
				$button
					.removeClass('btn-default')
					.addClass('btn-' + color + ' active');
			}
			else
			{
				$button
					.removeClass('btn-' + color + ' active')
					.addClass('btn-default');
			}
		}
		function init() {
			updateDisplay();
			// Inject the icon if applicable
			if ($button.find('.state-icon').length == 0) {
				$button.prepend('<i class="state-icon ' + settings[$button.data('state')].icon + '"></i> ');
			}
		}
		init();
	});
});
//-->
</script>
    
<?php } ?>